# Generated by Django 3.2.2 on 2021-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='work_arrangement',
            field=models.CharField(choices=[('Salon Based', 'Salon Based'), ('House Calls Only', 'House Calls Only'), ('Salon Based and House Calls', 'Salon Based and House Calls')], default='Salon Based', max_length=126),
        ),
    ]
