# Generated by Django 3.2.2 on 2021-05-10 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210510_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number has a minimum of 9 characters and a maximum of 15', regex='\\d{9,15}')]),
        ),
    ]
