# Generated by Django 3.2.2 on 2021-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_stylist_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='profile_pic',
            field=models.ImageField(default='stylist_app/default_stylist_180px.jpg', upload_to='profile_pics/'),
        ),
    ]
