# Generated by Django 3.2.2 on 2021-05-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_stylist_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_stylist_180px.jpg', upload_to='profile_pics/'),
        ),
    ]
