# Generated by Django 3.2.2 on 2021-05-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210512_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.region'),
        ),
    ]
