# Generated by Django 3.2.2 on 2021-05-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0004_auto_20210512_1131'),
        ('accounts', '0012_auto_20210513_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='default_stylist_180px.jpg', upload_to='portfolio_pics/')),
                ('hairstyle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stylist_app.hairstyle')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stylist_app.product')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stylist')),
            ],
        ),
    ]
