# Generated by Django 3.2.2 on 2021-05-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0004_auto_20210512_1131'),
        ('accounts', '0013_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, default='portfolio_pics/default_stylist_180px.jpg', upload_to='portfolio_pics/'),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='product',
            field=models.ManyToManyField(through='accounts.ProductOffering', to='stylist_app.Product'),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_stylist_180px.jpg', upload_to='profile_pics/'),
        ),
    ]
