# Generated by Django 3.2.2 on 2021-05-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210513_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='likes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
