# Generated by Django 3.2.2 on 2021-06-17 10:40

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_portfolio_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='profile_pics/default_stylist.png', upload_to='profile_pics/'),
        ),
    ]
