# Generated by Django 3.2.2 on 2021-06-17 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_stylist_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='bio',
            field=models.TextField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='work_arrangement',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MaxLengthValidator(60)]),
        ),
    ]
