# Generated by Django 3.2.2 on 2021-06-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210617_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='work_arrangement',
        ),
        migrations.AddField(
            model_name='serviceoffering',
            name='top_style',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stylist',
            name='house_calls',
            field=models.BooleanField(default=False),
        ),
    ]
