# Generated by Django 3.2.2 on 2021-06-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210618_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylist',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city'),
        ),
    ]
