# Generated by Django 3.2.2 on 2021-06-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_stylist_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city'),
        ),
    ]
