# Generated by Django 3.2.2 on 2021-06-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0005_auto_20210616_1549'),
        ('accounts', '0020_salon_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoffering',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_category', to='stylist_app.hairstylecategory'),
        ),
    ]
