# Generated by Django 3.2.2 on 2021-06-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_serviceoffering_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='portfolio_pics/default_stylist_180px.jpg', upload_to='portfolio_pics/'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='description',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='bio',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
