# Generated by Django 3.2.2 on 2021-06-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0006_alter_hairstyle_description'),
        ('accounts', '0023_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='hairstyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stylist_app.hairstyle'),
        ),
        migrations.AlterField(
            model_name='stylist',
            name='bio',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
