# Generated by Django 3.2.2 on 2021-06-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210624_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
