# Generated by Django 3.2.2 on 2021-07-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_portfolio_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stylist',
            old_name='hairstyle',
            new_name='hairstyles',
        ),
    ]
