# Generated by Django 3.2.2 on 2021-07-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0006_alter_hairstyle_description'),
        ('accounts', '0026_rename_hairstyle_stylist_hairstyles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoffering',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='style_categories', to='stylist_app.hairstylecategory'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='hairstyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_offers', to='stylist_app.hairstyle'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_hairstyles', to='accounts.stylist'),
        ),
    ]
