# Generated by Django 3.2.2 on 2021-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210704_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='bio',
            field=models.TextField(max_length=256),
        ),
    ]
