# Generated by Django 3.2.2 on 2021-08-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_stylist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='bio',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
