# Generated by Django 3.2.2 on 2021-09-22 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210921_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='criterion_1',
            new_name='craft',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='criterion_2',
            new_name='expectation',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='criterion_3',
            new_name='hygiene',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='criterion_4',
            new_name='professional',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='criterion_5',
            new_name='value',
        ),
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
