# Generated by Django 3.2.2 on 2021-09-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylist',
            name='rating',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
