# Generated by Django 3.2.2 on 2021-05-11 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stylisthairoffering',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stylistproductoffering',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
