# Generated by Django 3.2.2 on 2021-05-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_stylist_profile_pic'),
        ('stylist_app', '0002_auto_20210511_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=254)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offer', to='stylist_app.product')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_product', to='accounts.stylist')),
            ],
            options={
                'unique_together': {('product', 'stylist')},
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=254)),
                ('price', models.FloatField(blank=True, null=True)),
                ('hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_offer', to='stylist_app.hairstyle')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist_hairstyle', to='accounts.stylist')),
            ],
            options={
                'unique_together': {('hairstyle', 'stylist')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stylistproductoffering',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stylistproductoffering',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stylistproductoffering',
            name='stylist',
        ),
        migrations.DeleteModel(
            name='StylistHairOffering',
        ),
        migrations.DeleteModel(
            name='StylistProductOffering',
        ),
    ]
