# Generated by Django 3.2.2 on 2021-06-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0004_auto_20210512_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairstyleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='hairstyle_catergories/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('image', models.ImageField(blank=True, upload_to='product_catergories/')),
            ],
        ),
        migrations.AlterField(
            model_name='hairstyle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stylist_app.hairstylecategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stylist_app.productcategory'),
        ),
    ]
