# Generated by Django 3.2.2 on 2021-06-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0005_auto_20210616_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyle',
            name='description',
            field=models.TextField(blank=True, max_length=60),
        ),
    ]
