# Generated by Django 3.2.2 on 2021-10-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stylist_app', '0006_alter_hairstyle_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hairstyle',
            options={'ordering': ('name', 'category__name')},
        ),
    ]
